/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as TicketIssuesRouteImport } from './routes/ticket-issues'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IterationsRouteImport } from './routes/iterations'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ClockRouteImport } from './routes/clock'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as IndexRouteImport } from './routes/index'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIssuesRoute = TicketIssuesRouteImport.update({
  id: '/ticket-issues',
  path: '/ticket-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IterationsRoute = IterationsRouteImport.update({
  id: '/iterations',
  path: '/iterations',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockRoute = ClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/clock': typeof ClockRoute
  '/history': typeof HistoryRoute
  '/iterations': typeof IterationsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/ticket-issues': typeof TicketIssuesRoute
  '/todos': typeof TodosRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/clock': typeof ClockRoute
  '/history': typeof HistoryRoute
  '/iterations': typeof IterationsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/ticket-issues': typeof TicketIssuesRoute
  '/todos': typeof TodosRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/clock': typeof ClockRoute
  '/history': typeof HistoryRoute
  '/iterations': typeof IterationsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/ticket-issues': typeof TicketIssuesRoute
  '/todos': typeof TodosRoute
  '/trends': typeof TrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklists'
    | '/clock'
    | '/history'
    | '/iterations'
    | '/login'
    | '/settings'
    | '/ticket-issues'
    | '/todos'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklists'
    | '/clock'
    | '/history'
    | '/iterations'
    | '/login'
    | '/settings'
    | '/ticket-issues'
    | '/todos'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/checklists'
    | '/clock'
    | '/history'
    | '/iterations'
    | '/login'
    | '/settings'
    | '/ticket-issues'
    | '/todos'
    | '/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistsRoute: typeof ChecklistsRoute
  ClockRoute: typeof ClockRoute
  HistoryRoute: typeof HistoryRoute
  IterationsRoute: typeof IterationsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  TicketIssuesRoute: typeof TicketIssuesRoute
  TodosRoute: typeof TodosRoute
  TrendsRoute: typeof TrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket-issues': {
      id: '/ticket-issues'
      path: '/ticket-issues'
      fullPath: '/ticket-issues'
      preLoaderRoute: typeof TicketIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iterations': {
      id: '/iterations'
      path: '/iterations'
      fullPath: '/iterations'
      preLoaderRoute: typeof IterationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistsRoute: ChecklistsRoute,
  ClockRoute: ClockRoute,
  HistoryRoute: HistoryRoute,
  IterationsRoute: IterationsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  TicketIssuesRoute: TicketIssuesRoute,
  TodosRoute: TodosRoute,
  TrendsRoute: TrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
