// Code generated by tygo. DO NOT EDIT.

//////////
// source: models.go

export interface User {
  id: number /* int64 */;
  username: string;
  created_at: string;
}
export interface Attendance {
  id: number /* int64 */;
  user_id: number /* int64 */;
  date: string;
  clock_in?: string;
  clock_out?: string;
  status: string;
  is_overtime: boolean;
  created_at: string;
  updated_at: string;
}
export interface WorkLog {
  id: number /* int64 */;
  user_id: number /* int64 */;
  date: string;
  content: string;
  created_at: string;
  updated_at: string;
}
export interface Todo {
  id: number /* int64 */;
  user_id: number /* int64 */;
  content: string;
  url: string;
  done: boolean;
  created_at: string;
  updated_at: string;
}
export interface Checklist {
  id: number /* int64 */;
  user_id: number /* int64 */;
  title: string;
  items: string; // JSON 数组字符串
  created_at: string;
  updated_at: string;
}
export interface ChecklistSnapshot {
  id: number /* int64 */;
  user_id: number /* int64 */;
  checklist_id: number /* int64 */;
  title: string;
  items_hash: string;
  data: string; // JSON: { checked: bool[], notes: string[], extras: [...] }
  created_at: string;
}
export interface IterationOverride {
  id: number /* int64 */;
  user_id: number /* int64 */;
  iteration_number: number /* int64 */;
  start_date: string;
  end_date: string;
  created_at: string;
  updated_at: string;
}
export interface Passkey {
  id: number /* int64 */;
  name: string;
  created_at: string;
  last_used_at?: string;
}
/**
 * 数据导出结构
 */
export interface ExportData {
  attendance: Attendance[];
  work_logs: WorkLog[];
  todos: Todo[];
  checklists: Checklist[];
  checklist_snapshots: ChecklistSnapshot[];
  user_settings: { [key: string]: string};
  iteration_overrides: IterationOverride[];
  exported_at: string;
}

//////////
// source: responses.go

export interface MessageResponse {
  message: string;
}
export interface AuthResponse {
  token: string;
  user: User;
}
export interface MeResponse {
  user: User;
}
export interface AttendanceResponse {
  attendance?: Attendance;
}
export interface AttendanceListResponse {
  attendances: Attendance[];
}
export interface AttendanceStatsResponse {
  global_overtime_days: number /* int64 */;
  global_leave_days: number /* int64 */;
  global_remaining: number /* int64 */;
}
export interface WorkLogResponse {
  work_log?: WorkLog;
}
export interface WorkLogListResponse {
  work_logs: WorkLog[];
}
export interface TodoResponse {
  todo: Todo;
}
export interface TodoListResponse {
  todos: Todo[];
}
export interface ChecklistResponse {
  checklist: Checklist;
}
export interface ChecklistListResponse {
  checklists: Checklist[];
}
export interface SnapshotResponse {
  snapshot: ChecklistSnapshot;
}
export interface SnapshotListResponse {
  snapshots: ChecklistSnapshot[];
}
export interface IterationOverrideResponse {
  override: IterationOverride;
}
export interface IterationOverrideListResponse {
  overrides: IterationOverride[];
}
export interface SettingsResponse {
  timezone: string;
  kanban_url: string;
  theme: string;
  iteration_start_date: string;
  iteration_duration_days: string;
}
export interface VersionResponse {
  commit: string;
  date: string;
  content: string;
}
export interface VersionRangeResponse {
  earliest?: string;
  latest?: string;
}
export interface PasskeyListResponse {
  passkeys: Passkey[];
}
export interface PasskeyRegisterResponse {
  passkey: Passkey;
}
/**
 * PasskeyAuthBeginResponse 返回 WebAuthn 认证挑战参数
 */
export interface PasskeyAuthBeginResponse {
  challenge: string;
  challengeId: string;
  rpId: string;
  timeout: number /* int */;
  userVerification: string;
}
export interface DataImportResponse {
  message: string;
  attendance_count: number /* int */;
  work_log_count: number /* int */;
  todo_count: number /* int */;
  checklist_count: number /* int */;
  snapshot_count: number /* int */;
  override_count: number /* int */;
}
export interface DataDeleteResponse {
  message: string;
  attendance_count: number /* int64 */;
  work_log_count: number /* int64 */;
  todo_count: number /* int64 */;
}
