// Code generated by tygo. DO NOT EDIT.

//////////
// source: models.go

export interface User {
  id: number /* int64 */;
  username: string;
  created_at: string;
}
export interface Attendance {
  id: number /* int64 */;
  user_id: number /* int64 */;
  date: string;
  clock_in?: string;
  clock_out?: string;
  status: string;
  is_overtime: boolean;
  created_at: string;
  updated_at: string;
}
export interface WorkLog {
  id: number /* int64 */;
  user_id: number /* int64 */;
  date: string;
  content: string;
  created_at: string;
  updated_at: string;
}
export interface Todo {
  id: number /* int64 */;
  user_id: number /* int64 */;
  content: string;
  url: string;
  done: boolean;
  created_at: string;
  updated_at: string;
}
/**
 * TicketIssue 记录工单问题、根因分类和复盘结论。
 */
export interface TicketIssue {
  id: number /* int64 */;
  user_id: number /* int64 */;
  ticket_no: string;
  ticket_title: string;
  ticket_url: string;
  occurred_on: string;
  cause_type: string;
  problem_description: string;
  cause_detail: string;
  resolution: string;
  created_at: string;
  updated_at: string;
}
export interface Checklist {
  id: number /* int64 */;
  user_id: number /* int64 */;
  title: string;
  items: string; // JSON 数组字符串
  kind: string; // manual / daily_start / iteration_end
  created_at: string;
  updated_at: string;
}
export interface ChecklistRun {
  id: number /* int64 */;
  user_id: number /* int64 */;
  checklist_id: number /* int64 */;
  kind: string;
  occurrence_key: string;
  iteration_number?: number /* int64 */;
  title: string;
  items: string; // 创建进度时的清单项目快照
  data: string; // JSON: { checked: bool[], notes: string[] }
  completed: boolean;
  completed_at?: string;
  created_at: string;
  updated_at: string;
}
export interface ChecklistSnapshot {
  id: number /* int64 */;
  user_id: number /* int64 */;
  checklist_id: number /* int64 */;
  title: string;
  items_hash: string;
  data: string; // JSON: { checked: bool[], notes: string[], extras: [...] }
  created_at: string;
}
export interface IterationOverride {
  id: number /* int64 */;
  user_id: number /* int64 */;
  iteration_number: number /* int64 */;
  start_date: string;
  end_date: string;
  created_at: string;
  updated_at: string;
}
export interface Passkey {
  id: number /* int64 */;
  name: string;
  created_at: string;
  last_used_at?: string;
}
export interface PendingReminder {
  id: number /* int64 */;
  user_id: number /* int64 */;
  send_at: string;
  attempts: number /* int */;
  created_at: string;
}
/**
 * PushSubscription 浏览器推送订阅信息
 */
export interface PushSubscription {
  id: number /* int64 */;
  user_id: number /* int64 */;
  endpoint: string;
  p256dh: string;
  auth: string;
  created_at: string;
}
/**
 * 数据导出结构
 */
export interface ExportData {
  attendance: Attendance[];
  work_logs: WorkLog[];
  todos: Todo[];
  ticket_issues: TicketIssue[];
  checklists: Checklist[];
  checklist_runs: ChecklistRun[];
  checklist_snapshots: ChecklistSnapshot[];
  user_settings: { [key: string]: string};
  iteration_overrides: IterationOverride[];
  exported_at: string;
}

//////////
// source: responses.go

export interface MessageResponse {
  message: string;
}
export interface AuthResponse {
  token: string;
  user: User;
}
export interface MeResponse {
  user: User;
}
export interface AttendanceResponse {
  attendance?: Attendance;
}
export interface AttendanceListResponse {
  attendances: Attendance[];
}
export interface AttendanceStatsResponse {
  global_overtime_days: number /* int64 */;
  global_leave_days: number /* int64 */;
  global_remaining: number /* int64 */;
}
export interface WorkLogResponse {
  work_log?: WorkLog;
}
export interface WorkLogListResponse {
  work_logs: WorkLog[];
}
export interface TodoResponse {
  todo: Todo;
}
export interface TodoListResponse {
  todos: Todo[];
}
export interface TicketIssueResponse {
  ticket_issue: TicketIssue;
}
export interface TicketIssueListResponse {
  ticket_issues: TicketIssue[];
}
export interface TicketIssueStatsResponse {
  total_count: number /* int64 */;
  code_count: number /* int64 */;
  operation_count: number /* int64 */;
}
export interface ChecklistResponse {
  checklist: Checklist;
}
export interface ChecklistListResponse {
  checklists: Checklist[];
}
export interface SnapshotResponse {
  snapshot: ChecklistSnapshot;
}
export interface SnapshotListResponse {
  snapshots: ChecklistSnapshot[];
}
export interface ChecklistRunResponse {
  run: ChecklistRun;
}
export interface ChecklistReminder {
  kind: string;
  occurrence_key: string;
  label: string;
  due_date: string;
  iteration_number?: number /* int64 */;
  iteration_start?: string;
  iteration_end?: string;
  checklist: Checklist;
  run?: ChecklistRun;
}
export interface ChecklistReminderListResponse {
  reminders: ChecklistReminder[];
}
export interface IterationOverrideResponse {
  override: IterationOverride;
}
export interface IterationOverrideListResponse {
  overrides: IterationOverride[];
}
export interface SettingsResponse {
  timezone: string;
  kanban_url: string;
  theme: string;
  iteration_start_date: string;
  iteration_duration_days: string;
  reminder_delay: string;
}
export interface VersionResponse {
  commit: string;
  date: string;
  content: string;
}
export interface VersionRangeResponse {
  earliest?: string;
  latest?: string;
}
export interface PasskeyListResponse {
  passkeys: Passkey[];
}
export interface PasskeyRegisterResponse {
  passkey: Passkey;
}
/**
 * PasskeyAuthBeginResponse 返回 WebAuthn 认证挑战参数
 */
export interface PasskeyAuthBeginResponse {
  challenge: string;
  challengeId: string;
  rpId: string;
  timeout: number /* int */;
  userVerification: string;
}
export interface DataImportResponse {
  message: string;
  attendance_count: number /* int */;
  work_log_count: number /* int */;
  todo_count: number /* int */;
  ticket_issue_count: number /* int */;
  checklist_count: number /* int */;
  checklist_run_count: number /* int */;
  snapshot_count: number /* int */;
  override_count: number /* int */;
}
export interface DataDeleteResponse {
  message: string;
  attendance_count: number /* int64 */;
  work_log_count: number /* int64 */;
  todo_count: number /* int64 */;
  ticket_issue_count: number /* int64 */;
}
export interface VapidKeyResponse {
  public_key: string;
}
export interface PushSubscribeRequest {
  endpoint: string;
  p256dh: string;
  auth: string;
}
/**
 * SyncConfigResponse WebDAV 配置信息（密码脚敏信息不返回）
 */
export interface SyncConfigResponse {
  configured: boolean;
  webdav_url: string;
  webdav_username: string;
  remote_path: string;
  auto_sync_interval_minutes: number /* int */;
  created_at: string;
  updated_at: string;
  warning?: string;
}
/**
 * SyncStatusResponse 当前同步状态
 */
export interface SyncStatusResponse {
  configured: boolean;
  last_sync_at?: string;
  last_direction?: string;
  last_local_hash?: string;
  last_remote_hash?: string;
}
/**
 * SyncCheckResponse 冲突检测结果
 */
export interface SyncCheckResponse {
  status: string; // ok / conflict / remote_ahead / local_ahead / no_config / first_sync
  current_local_hash: string;
  current_remote_hash: string;
  last_local_hash: string;
  last_remote_hash: string;
  message: string;
}
/**
 * SyncOperationResponse push/pull 操作结果
 */
export interface SyncOperationResponse {
  message: string;
  local_hash: string;
  remote_hash: string;
}
/**
 * SyncConflictResponse 冲突响应（HTTP 409）
 */
export interface SyncConflictResponse {
  error: string;
  current_local_hash: string;
  current_remote_hash: string;
  last_local_hash: string;
  last_remote_hash: string;
}
/**
 * SyncLogListResponse 同步日志列表
 */
export interface SyncLogListResponse {
  logs: SyncLog[];
}
/**
 * SyncValidateResponse 验证 WebDAV 连接结果
 */
export interface SyncValidateResponse {
  success: boolean;
  message: string;
}

//////////
// source: sync_types.go

/**
 * SyncConfig 存储 WebDAV 连接配置（敏感字段加密后入库）
 */
export interface SyncConfig {
  id: number /* int64 */;
  user_id: number /* int64 */;
  webdav_url: string;
  webdav_username: string;
  remote_path: string;
  auto_sync_interval_minutes: number /* int */;
  created_at: string;
  updated_at: string;
}
/**
 * SyncState 记录每次成功同步后的状态快照
 */
export interface SyncState {
  id: number /* int64 */;
  user_id: number /* int64 */;
  last_local_hash: string;
  last_remote_hash: string;
  last_sync_at: string;
  direction: string; // push / pull
}
/**
 * SyncLog 记录每次同步操作的详细日志
 */
export interface SyncLog {
  id: number /* int64 */;
  user_id: number /* int64 */;
  direction: string; // push / pull / check
  status: string; // success / conflict / error
  message: string;
  created_at: string;
}
/**
 * WebDAV 远端 manifest 文件结构
 */
export interface SyncManifest {
  version: number /* int */;
  snapshot_file: string;
  snapshot_hash: string;
  pushed_at: string;
}
/**
 * EncryptedMasterKey 存储在 WebDAV 上的加密主密钥
 */
export interface EncryptedMasterKey {
  salt: string;
  encrypted: string;
}
