// Code generated by tygo. DO NOT EDIT.

//////////
// source: models.go

/**
 * RecordID 是 PocketBase record ID；反序列化时兼容旧版备份中的数字 ID。
 */
export type RecordID = string;
export interface User {
  id: RecordID;
  username: string;
  created_at: string;
}
export interface Attendance {
  id: RecordID;
  user_id: RecordID;
  date: string;
  clock_in?: string;
  clock_out?: string;
  status: string;
  is_overtime: boolean;
  created_at: string;
  updated_at: string;
}
export interface WorkLog {
  id: RecordID;
  user_id: RecordID;
  date: string;
  content: string;
  created_at: string;
  updated_at: string;
}
export interface Todo {
  id: RecordID;
  user_id: RecordID;
  content: string;
  url: string;
  done: boolean;
  created_at: string;
  updated_at: string;
}
/**
 * TicketIssue 记录工单问题、根因分类和复盘结论。
 */
export interface TicketIssue {
  id: RecordID;
  user_id: RecordID;
  ticket_no: string;
  ticket_title: string;
  ticket_url: string;
  occurred_on: string;
  cause_type: string;
  problem_description: string;
  cause_detail: string;
  resolution: string;
  created_at: string;
  updated_at: string;
}
export interface Checklist {
  id: RecordID;
  user_id: RecordID;
  title: string;
  items: string; // JSON 数组字符串
  kind: string; // 固定为 manual，保留以兼容旧备份
  created_at: string;
  updated_at: string;
}
export interface ChecklistSnapshot {
  id: RecordID;
  user_id: RecordID;
  checklist_id: RecordID;
  title: string;
  items_hash: string;
  data: string; // JSON: { checked: bool[], notes: string[], extras: [...] }
  created_at: string;
}
export interface IterationOverride {
  id: RecordID;
  user_id: RecordID;
  iteration_number: number /* int64 */;
  start_date: string;
  end_date: string;
  created_at: string;
  updated_at: string;
}
/**
 * HolidayCalendarDay 只保存中国法定节假日与调休工作日等例外日期。
 */
export interface HolidayCalendarDay {
  id: RecordID;
  user_id: RecordID;
  date: string;
  is_workday: boolean;
  name: string;
  source: string;
  created_at: string;
  updated_at: string;
}
export interface HolidayCalendarImportDay {
  date: string;
  is_workday: boolean;
  name: string;
}
export interface HolidayCalendarImportRequest {
  days: HolidayCalendarImportDay[];
  replace_years: boolean;
  source: string;
}
export interface SettingsUpdateRequest {
  timezone?: string;
  theme?: string;
  iteration_start_date?: string;
  iteration_duration_days?: string; // 兼容旧客户端
  iteration_workdays?: string;
  reminder_delay?: string;
}
/**
 * 数据导出结构
 */
export interface ExportData {
  attendance: Attendance[];
  work_logs: WorkLog[];
  todos: Todo[];
  ticket_issues: TicketIssue[];
  checklists: Checklist[];
  checklist_snapshots: ChecklistSnapshot[];
  user_settings: { [key: string]: string};
  iteration_overrides: IterationOverride[];
  holiday_calendar: HolidayCalendarDay[];
  exported_at: string;
}

//////////
// source: responses.go

export interface MessageResponse {
  message: string;
}
export interface AuthResponse {
  token: string;
  user: User;
}
export interface MeResponse {
  user: User;
}
export interface AttendanceResponse {
  attendance?: Attendance;
}
export interface AttendanceListResponse {
  attendances: Attendance[];
}
export interface AttendanceStatsResponse {
  global_overtime_days: number /* int64 */;
  global_leave_days: number /* int64 */;
  global_remaining: number /* int64 */;
}
export interface WorkLogResponse {
  work_log?: WorkLog;
}
export interface WorkLogListResponse {
  work_logs: WorkLog[];
}
export interface TodoResponse {
  todo: Todo;
}
export interface TodoListResponse {
  todos: Todo[];
}
export interface TicketIssueResponse {
  ticket_issue: TicketIssue;
}
export interface TicketIssueListResponse {
  ticket_issues: TicketIssue[];
}
export interface TicketIssueStatsResponse {
  total_count: number /* int64 */;
  code_count: number /* int64 */;
  operation_count: number /* int64 */;
}
export interface ChecklistResponse {
  checklist: Checklist;
}
export interface ChecklistListResponse {
  checklists: Checklist[];
}
export interface SnapshotResponse {
  snapshot: ChecklistSnapshot;
}
export interface SnapshotListResponse {
  snapshots: ChecklistSnapshot[];
}
export interface IterationOverrideResponse {
  override: IterationOverride;
}
export interface IterationOverrideListResponse {
  overrides: IterationOverride[];
}
export interface IterationRange {
  iteration_number: number /* int64 */;
  start_date: string;
  end_date: string;
  calendar_days: number /* int */;
  workdays: number /* int */;
  is_overridden: boolean;
}
export interface IterationListResponse {
  current_iteration: number /* int64 */;
  iterations: IterationRange[];
}
export interface HolidayCalendarYearSummary {
  year: number /* int */;
  day_count: number /* int */;
  holiday_count: number /* int */;
  workday_count: number /* int */;
}
export interface HolidayCalendarResponse {
  days: HolidayCalendarDay[];
  years: HolidayCalendarYearSummary[];
}
export interface HolidayCalendarImportResponse {
  imported_count: number /* int */;
  replaced_years: number /* int */[];
}
export interface SettingsResponse {
  timezone: string;
  theme: string;
  iteration_start_date: string;
  iteration_duration_days: string; // 兼容旧客户端
  iteration_workdays: string;
  reminder_delay: string;
}
export interface VersionResponse {
  commit: string;
  date: string;
  content: string;
}
export interface VersionRangeResponse {
  earliest?: string;
  latest?: string;
}
export interface DataImportResponse {
  message: string;
  attendance_count: number /* int */;
  work_log_count: number /* int */;
  todo_count: number /* int */;
  ticket_issue_count: number /* int */;
  checklist_count: number /* int */;
  snapshot_count: number /* int */;
  override_count: number /* int */;
  calendar_day_count: number /* int */;
}
export interface DataDeleteResponse {
  message: string;
  attendance_count: number /* int64 */;
  work_log_count: number /* int64 */;
  todo_count: number /* int64 */;
  ticket_issue_count: number /* int64 */;
}
